//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebCS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(double sumando1, double sumando2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(double sumando1, double sumando2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        double Resta(double minuendo, double sustraendo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RestaAsync(double minuendo, double sustraendo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        double Multiplicar(double multiplicando, double multiplicador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplicarAsync(double multiplicando, double multiplicador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        double Dividir(double Dividendo, double Divisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DividirAsync(double Dividendo, double Divisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        double Potencia(double Base, double Exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Potencia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PotenciaAsync(double Base, double Exponente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Radicacion", ReplyAction="*")]
        double Radicacion(double Radicando);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Radicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RadicacionAsync(double Radicando);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Porcentaje", ReplyAction="*")]
        double Porcentaje(double nro1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Porcentaje", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PorcentajeAsync(double nro1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fact", ReplyAction="*")]
        double fact(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fact", ReplyAction="*")]
        System.Threading.Tasks.Task<double> factAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seno", ReplyAction="*")]
        double Seno(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seno", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SenoAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Coseno", ReplyAction="*")]
        double Coseno(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Coseno", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CosenoAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteWebCS.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteWebCS.ServiceReference1.WebService1Soap>, ClienteWebCS.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Suma(double sumando1, double sumando2) {
            return base.Channel.Suma(sumando1, sumando2);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(double sumando1, double sumando2) {
            return base.Channel.SumaAsync(sumando1, sumando2);
        }
        
        public double Resta(double minuendo, double sustraendo) {
            return base.Channel.Resta(minuendo, sustraendo);
        }
        
        public System.Threading.Tasks.Task<double> RestaAsync(double minuendo, double sustraendo) {
            return base.Channel.RestaAsync(minuendo, sustraendo);
        }
        
        public double Multiplicar(double multiplicando, double multiplicador) {
            return base.Channel.Multiplicar(multiplicando, multiplicador);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicarAsync(double multiplicando, double multiplicador) {
            return base.Channel.MultiplicarAsync(multiplicando, multiplicador);
        }
        
        public double Dividir(double Dividendo, double Divisor) {
            return base.Channel.Dividir(Dividendo, Divisor);
        }
        
        public System.Threading.Tasks.Task<double> DividirAsync(double Dividendo, double Divisor) {
            return base.Channel.DividirAsync(Dividendo, Divisor);
        }
        
        public double Potencia(double Base, double Exponente) {
            return base.Channel.Potencia(Base, Exponente);
        }
        
        public System.Threading.Tasks.Task<double> PotenciaAsync(double Base, double Exponente) {
            return base.Channel.PotenciaAsync(Base, Exponente);
        }
        
        public double Radicacion(double Radicando) {
            return base.Channel.Radicacion(Radicando);
        }
        
        public System.Threading.Tasks.Task<double> RadicacionAsync(double Radicando) {
            return base.Channel.RadicacionAsync(Radicando);
        }
        
        public double Porcentaje(double nro1) {
            return base.Channel.Porcentaje(nro1);
        }
        
        public System.Threading.Tasks.Task<double> PorcentajeAsync(double nro1) {
            return base.Channel.PorcentajeAsync(nro1);
        }
        
        public double fact(int numero) {
            return base.Channel.fact(numero);
        }
        
        public System.Threading.Tasks.Task<double> factAsync(int numero) {
            return base.Channel.factAsync(numero);
        }
        
        public double Seno(int numero) {
            return base.Channel.Seno(numero);
        }
        
        public System.Threading.Tasks.Task<double> SenoAsync(int numero) {
            return base.Channel.SenoAsync(numero);
        }
        
        public double Coseno(int numero) {
            return base.Channel.Coseno(numero);
        }
        
        public System.Threading.Tasks.Task<double> CosenoAsync(int numero) {
            return base.Channel.CosenoAsync(numero);
        }
    }
}
