'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function Suma(ByVal sumando1 As Double, ByVal sumando2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function SumaAsync(ByVal sumando1 As Double, ByVal sumando2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal minuendo As Double, ByVal sustraendo As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal minuendo As Double, ByVal sustraendo As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function Multiplicar(ByVal multiplicando As Double, ByVal multiplicador As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function MultiplicarAsync(ByVal multiplicando As Double, ByVal multiplicador As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function Dividir(ByVal Dividendo As Double, ByVal Divisor As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function DividirAsync(ByVal Dividendo As Double, ByVal Divisor As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal Base As Double, ByVal Exponente As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal Base As Double, ByVal Exponente As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Radicacion", ReplyAction:="*")>  _
        Function Radicacion(ByVal Radicando As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Radicacion", ReplyAction:="*")>  _
        Function RadicacionAsync(ByVal Radicando As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Porcentaje", ReplyAction:="*")>  _
        Function Porcentaje(ByVal nro1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Porcentaje", ReplyAction:="*")>  _
        Function PorcentajeAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/fact", ReplyAction:="*")>  _
        Function fact(ByVal numero As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/fact", ReplyAction:="*")>  _
        Function factAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal numero As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function Coseno(ByVal numero As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function CosenoAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Suma(ByVal sumando1 As Double, ByVal sumando2 As Double) As Double Implements ServiceReference1.WebService1Soap.Suma
            Return MyBase.Channel.Suma(sumando1, sumando2)
        End Function
        
        Public Function SumaAsync(ByVal sumando1 As Double, ByVal sumando2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumaAsync
            Return MyBase.Channel.SumaAsync(sumando1, sumando2)
        End Function
        
        Public Function Resta(ByVal minuendo As Double, ByVal sustraendo As Double) As Double Implements ServiceReference1.WebService1Soap.Resta
            Return MyBase.Channel.Resta(minuendo, sustraendo)
        End Function
        
        Public Function RestaAsync(ByVal minuendo As Double, ByVal sustraendo As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(minuendo, sustraendo)
        End Function
        
        Public Function Multiplicar(ByVal multiplicando As Double, ByVal multiplicador As Double) As Double Implements ServiceReference1.WebService1Soap.Multiplicar
            Return MyBase.Channel.Multiplicar(multiplicando, multiplicador)
        End Function
        
        Public Function MultiplicarAsync(ByVal multiplicando As Double, ByVal multiplicador As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MultiplicarAsync
            Return MyBase.Channel.MultiplicarAsync(multiplicando, multiplicador)
        End Function
        
        Public Function Dividir(ByVal Dividendo As Double, ByVal Divisor As Double) As Double Implements ServiceReference1.WebService1Soap.Dividir
            Return MyBase.Channel.Dividir(Dividendo, Divisor)
        End Function
        
        Public Function DividirAsync(ByVal Dividendo As Double, ByVal Divisor As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.DividirAsync
            Return MyBase.Channel.DividirAsync(Dividendo, Divisor)
        End Function
        
        Public Function Potencia(ByVal Base As Double, ByVal Exponente As Double) As Double Implements ServiceReference1.WebService1Soap.Potencia
            Return MyBase.Channel.Potencia(Base, Exponente)
        End Function
        
        Public Function PotenciaAsync(ByVal Base As Double, ByVal Exponente As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(Base, Exponente)
        End Function
        
        Public Function Radicacion(ByVal Radicando As Double) As Double Implements ServiceReference1.WebService1Soap.Radicacion
            Return MyBase.Channel.Radicacion(Radicando)
        End Function
        
        Public Function RadicacionAsync(ByVal Radicando As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RadicacionAsync
            Return MyBase.Channel.RadicacionAsync(Radicando)
        End Function
        
        Public Function Porcentaje(ByVal nro1 As Double) As Double Implements ServiceReference1.WebService1Soap.Porcentaje
            Return MyBase.Channel.Porcentaje(nro1)
        End Function
        
        Public Function PorcentajeAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PorcentajeAsync
            Return MyBase.Channel.PorcentajeAsync(nro1)
        End Function
        
        Public Function fact(ByVal numero As Integer) As Double Implements ServiceReference1.WebService1Soap.fact
            Return MyBase.Channel.fact(numero)
        End Function
        
        Public Function factAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.factAsync
            Return MyBase.Channel.factAsync(numero)
        End Function
        
        Public Function Seno(ByVal numero As Integer) As Double Implements ServiceReference1.WebService1Soap.Seno
            Return MyBase.Channel.Seno(numero)
        End Function
        
        Public Function SenoAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SenoAsync
            Return MyBase.Channel.SenoAsync(numero)
        End Function
        
        Public Function Coseno(ByVal numero As Integer) As Double Implements ServiceReference1.WebService1Soap.Coseno
            Return MyBase.Channel.Coseno(numero)
        End Function
        
        Public Function CosenoAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.CosenoAsync
            Return MyBase.Channel.CosenoAsync(numero)
        End Function
    End Class
End Namespace
